# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "SS2Gt%z8Ljg4x2M$0gR$dIcHcdDBsC2R1hN4"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "xxnDR*7$chnTLW#%k7j4w0&9b2lN@Yterzt7"
    salt: "@38g*amo9bb^Tc7jIA9p6tumLquVxP9GO*4o"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  randomstack.me:
    env:
      db_password: "tr3ZNLVoP!3R%SJrVm8FsZ33%iFqn7W4J6b7"
      # Generate your keys here: https://roots.io/salts.html
auth_key: ",y{Vat%kr6?WdjkWzrS3lz5s#fa:r4SOA&eIR.y35|/sn{9Z]>#+T}xH!K^&>=Hs"
secure_auth_key: "u(K@[PwJUc6O4OLfkAgdFJ9{yyc5HnX27y&msGN^X,rrHt43`{b`R)}Z_ms;T;(`"
logged_in_key: "Q>l.]4tZ#dHA`s!4jy{@uzj#oC.RQBkC;aF*S@I@lUmYBowX9WBVO+SnT&Umh`Cv"
nonce_key: "V,cj_*eZhRQU^k2oL{9)tY(JgR.B[N|*9}_$PR&>*&SSxE,i]Yo.+&d|Y;ARzh-s"
auth_salt: "Lp]l7T&b8&/H:2ayE$WinV;_-eU/l^Ty%*8@8#X/L]T`$lHMFTWDjHooKXJa);)!"
secure_auth_salt: "_tDB-8d-OysKKdL|+H>zVmLtimqm&I{i6)jre9z6XK%HCV^HD3Y[jUkK%*n%Z$+/"
logged_in_salt: "VdXWlq}6qkS>C[S:n_ZNQfC<r0Q&?t<7xk(J[>q;3(=7J2c@R^z}4T[rM}lg.<tH"
nonce_salt: "y..>xXD)ymy=*-]N0C]C/vSzV(i%+2&i,vS#=r>#lR$-rsh<KKnW+^&-kHd@4WmM"
